### ISSUE TITLE
[6주차 프론트엔드 파트]피그마 템플릿 선정 및 피그마 공부

### ISSUE THREAD

**Issue by Chominsu98** [PocketBand/frontend-web#19]
## 할일
-  [피그마 템플릿](https://www.figma.com/community/category/mobile-apps)
- 여기에서 우리 서비스에 어울릴 것 같은 전체 템플릿 인당 2개씩 정도 선정 진행 후 여기 이슈에 댓글로 공유해주세요
-  월요일 9시 템플릿 최종 선정 후 > 각 영역별로 디자인 설계서 기반 디자인 진행

## 디자인 진행 과정
- 전체 템플릿을 선정 하고 해당 템플릿에서 제공하는 컴포넌트 모양과 디자인들을 우리는MUI로 최대한 비슷하게 만들며 설계해 나갈 예정

## 일정
- 2024년 04월 29일 까지

**Comment by Chominsu98** [comment]
## [템플릿 추천]
1. [Spark View]( https://www.figma.com/community/file/1361033924384271987/spark-view-enhancing-ott-engagement)

![image](https://github.com/PocketBand/frontend-web/assets/37100067/b44a40c2-2614-4f43-ad93-c591c093d547)

> 추천사유: 우선 우리 로고의 컬러 조합이 동일하며 커뮤니쪽에서 쓸 수 있는 카드나 숏츠 형식에 적합함
또한 Bottom Navigation 구성 또한 우리 구성이랑 동일함 

- 커뮤니티쪽 페이지에서 잘 쓸 수 있을 것 같음

 _물론 로고 또한 금방 색 바꿀 수 있어서 브랜드 컬러에 너무 고려안해도 됨_


2. [Travel App](https://www.figma.com/community/file/1363192247664787842/travel-app)
![image](https://github.com/PocketBand/frontend-web/assets/37100067/a725e92c-1e90-4a9b-b9fa-feebd880f45d)
> 추천 사유: 전체적인 커뮤니티쪽 페이지 진행시 괜찮을 것 같음

3.[AR Map]( https://www.figma.com/community/file/827241527209963356/ar-map?searchSessionId=lvdvsr1s-onwqd47kea)

![Image](https://github.com/PocketBand/frontend-web/assets/37100067/e1f404b4-db04-481d-ae10-245c7f6ded19)

> 추천 사유: 지도페이지 쪽은 해당 UI를 쓰기에 좋을 것 같음(검색창, 마커 선택 시 해당 하단 카드 등)

**Comment by Chominsu98** [comment]
## 정상이 템플릿 추천

1) [SnapShot](https://www.figma.com/community/file/1355690087460264916/snapshop-e-commerce-mobile-kit-builder)

2) [Shoppe](https://www.figma.com/community/file/1321464360558173342/shoppe-ecommerce-clothing-fashion-store-multi-purpose-ui-mobile-app-design)

**Comment by Oneul1213** [comment]
공통 선정 기준
- 사용할 수 있는 화면이 많은 것
- 우리 앱에 있는 컴포넌트들 대부분이 있는 것

1. [SnapShot](https://www.figma.com/community/file/1355690087460264916/snapshop-e-commerce-mobile-kit-builder)

    - 바텀네비, 바텀시트, 서브헤더, 카드 형식(커뮤니티), 지도, 카메라, 설정, 로그인 등 다양한 컴포넌트 보유

2. [Shoppe](https://www.figma.com/community/file/1321464360558173342/shoppe-ecommerce-clothing-fashion-store-multi-purpose-ui-mobile-app-design)
    - 리뷰, 캘린더, 다양한 팝업, 아바타(밴드 프로필)

**Comment by Chominsu98** [comment]
<완료>

## 최종 템플릿 기반 선정

- shoppe 기준으로 기반 깔고 그 위에서 페이지별로 다른 페이지 차용 예정

## 역할 분담
- 민수: 프로토타입 제작 및 주제색 강조색 배경색 보조색 선정
- 정상,재하 : 컴포넌트별 디자인 시작
