### ISSUE TITLE
[1주차 진행][아이디어 제안]

### ISSUE THREAD

**Issue by Chominsu98** [PocketBand/frontend-web#3]
## 아이디어 제안

밴드-포켓밴드 (민수ver)

<지도 영역>
- 합주실예약(지도-카카오 지도api),
   (상세)
      - 지점, 위치 검색
       - 현재 위치(geolocation) 기반 근방 합주실 위치 
       - 각 합주실 특징 및 리뷰
       - (네이버 예약 가능 지점인 경우) 공석,시간대 확인 가능하게--->
       - 즐겨찾기 지점 특정시간대 빌 경우 카카오톡 api로 알려주기
       - 정기적으로 (crontab) 예약 가능하게 하는 정기 예약 시스템 
       -많이 찾는 합주실 지역별 추천(리뷰수)

      -자체 리뷰 및 즐겨찾기
      -외부 링크 공유(다른 플랫폼으로의 링크공유)

<밴드생활>
  
  - 악기별(기타,드럼,피아노 등) 추천 레슨,컨텐츠 등 추천(릴스,인스타계정)

-  날짜별 밴드 문화생활 정보 츄천
-  우리 밴드 자랑하기 또는 기록모음

(합주 작업실 도구모음)
<영상녹화>
 -모니터링(영상녹화-숏컷으로 짧은동선으로 바로 녹화 가능하도록)
소리또는 특정행동모션으로 녹화시작중단

<오디오>
- 튜너 기능

<악보서치>
  -- 곡 악보(정보-배치성 주기적 데이터 )
   (상세)
       - (유료)  악보바다 등 각종 악보 사이트 크롤링 ( 링크,이미지 ) 
       - (무료) 구글에서 악보 크롤링

**Comment by jaehawilly** [comment]
- 나만의 즐겨찾는 합주실 즐겨찾기 기능
- 합주실을 주 고객으로, 합주실만의 광고나 솔직리뷰 작성이 가능한 플랫폼(리뷰 작성 시 확실한 손님이라는 검사할 수 있는 기능, 모두닥이라는 어플에서 아이디어 따옴)
