### ISSUE TITLE
[2주차 진행][기술 검토]

### ISSUE THREAD

**Issue by Chominsu98** [PocketBand/frontend-web#7]
### Discussed in https://github.com/orgs/PocketBand/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **jaehawilly** March 26, 2024</sup>
[기술 검토]

<재하>
- 합주실예약(지도-카카오, 네이버 지도api)
- 정산 메시지 카톡 자동 전송(카카오톡 알림 api)

<두열&정원>
- 리뷰 작성시 솔직리뷰 validation 체크 로직 기반 합주실 리뷰(모두닥)
- 보안 검토(jwt, 채팅)

<정상>
- 인스타, 유튜브 컨텐츠 크롤링 기능(데이터 크기 검토)
- 악보 크롤링 기능
- 콘텐츠 추천 기능

<민수>
- 영상 녹화 모니터링 기능
- 오디오 튜너 기능
- 각 밴드별을 나타내는 그래픽요소 어필 (꾸미기 기능)--싸이월드 같은 느낌</div>

**Comment by Chominsu98** [comment]
<3d 그래픽>
1.React Three Fiber 학습이 별도로 필요하긴 할듯,,,,
(공부시간이 조금 필요)
(원툴)
> https://codesandbox.io/s/42glz0

<카메라 녹화 제어>
<영상촬영>
1.react-webcam
(장점)
- 저번에 졸작때 쓴 거이자 가장 다빈도 사용되는 컴포넌트

(단점)
-모바일 진행시 카메라 해상도가 안 맞음

2.react-html5-camera-photo
(단점)
- IOS는 safari에서만 구동 가능

3.react-camera-pro
(장점)
 - 카메라 화면자체가 반응형이라 좋음
 - 모바일 맞춤 컴포넌트

4.(웹)위 중에 선택 +(모바일)Pwa활용한 네이티브 카메라 앱 호출

(제한):pwa로 네이티브 카메라 앱 자체 호출은 (앨범 내 업로드)시 사용 가능
하지만, 특정 액션으로 제어하기 위해서는 (네이티브 카메라 앱)내에서는 불가


===============
<결론>
react-camera-pro + react-resonponsive(모바일,웹 훅스)+pwa

<행동으로 제어>
tensorflow pose detection

**Comment by jaehawilly** [comment]
# Kakao 지도 API

1일 300,000회 무료 이용 가능

**Kakao 지도 API** 는 키 발급을 받아야 사용할 수 있습니다.
그리고 키를 발급받기 위해서는 카카오 계정이 필요합니다.

키 발급에는 아래 과정이 필요합니다.

1. [카카오 개발자사이트](https://developers.kakao.com/) (https://developers.kakao.com) 접속
2. 개발자 등록 및 앱 생성
3. 웹 플랫폼 추가: 앱 선택 – [플랫폼] – [Web 플랫폼 등록] – 사이트 도메인 등록
4. 사이트 도메인 등록: [웹] 플랫폼을 선택하고, [사이트 도메인] 을 등록합니다. (예: http://localhost:8080)
5. 페이지 상단의 [JavaScript 키]를 지도 API의 appkey로 사용합니다.
6. 앱을 실행합니다.

**[앱 등록]**

![image](https://github.com/PocketBand/frontend-web/assets/37172636/3004b8ad-cdc4-40fc-b792-acdcb147815a)

**[플랫폼 설정]**

![image](https://github.com/PocketBand/frontend-web/assets/37172636/e55daa87-8274-40be-a8a6-7fe878d7f97f)

ex> http://localhost:8080 로 등록

```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>Kakao 지도 시작하기</title>
</head>
<body>
	<div id="map" style="width:500px;height:400px;"></div>
	<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=발급받은 APP KEY를 넣으시면 됩니다."></script>
	<script>
		var container = document.getElementById('map');
		var options = {
			center: new kakao.maps.LatLng(33.450701, 126.570667),
			level: 3
		};

		var map = new kakao.maps.Map(container, options);
	</script>
</body>
</html>
```

**[카테고리 별 장소 선택 가능]**

![Image](https://github.com/PocketBand/frontend-web/assets/37172636/033d2ddd-975c-4575-b84e-d94283779332)


# Kakao 알림톡 API

https://developers.kakao.com/docs/latest/ko/message/js


![Image](https://github.com/PocketBand/frontend-web/assets/37172636/c9cf1d67-14c9-40c9-bad2-49a7be307937)

**Comment by Chominsu98** [comment]
## 카카오 맵에서 상세정보 불러오기 가능 방안 탐색

- 실제 서비스 분석해본 결과 
- 카카오맵은 상세정보 불러올 때 REST방식 GET으로 불러옴 (따라서 직접 호출해볼 경우 JSON 반환)
- 별도 막혀있지 않음(공식 사이트상 제공 api는 아니지만 사용 가능 할 것으로 보임)
- 단지 Proxy로 Cors에러만 피해주면 가능할듯


![Image](https://github.com/PocketBand/frontend-web/assets/37100067/80626402-e106-4786-8ee4-7f098a0361fc)

> 응답값


![Image](https://github.com/PocketBand/frontend-web/assets/37100067/27577e64-542a-40da-89a9-4be382a50984)


### 네이버 맵은 불가

- 네이버맵은 애초에 GraphQl로 엔드포인트가 하나로 파악 불가...

![Image](https://github.com/PocketBand/frontend-web/assets/37100067/56a10208-ef6f-434b-888a-4f005b3b8a1b)

>응답값

![Image](https://github.com/PocketBand/frontend-web/assets/37100067/bf20946f-4b59-4ac0-b547-927e9e766a61)
